- 👋 Hi, I’m @sCarter0 
- 👀 I’m interested in becoming an upcoming nail artist ...
- 🌱 I’m currently learning fashion and artists work ...
- 💞️ I’m looking to collaborate on Designing and beautishan  ...
- 📫 How to reach me on Instagram @liilfineassherselfff , on Facebook @shakeria.carter.90...

<!---
sCarter0/sCarter0 is a ✨ special ✨ repository because its `Nails thats falling and you need to come let your nails feel my brush breeze .
